### ISSUE TITLE
Mongoose-os-apps

### ISSUE THREAD

**Issue by aoudiamoncef** [mongoose-os-libs/mq135#1]
Hello @cpq 

Please , could you grant access to [apps repository](https://github.com/mongoose-os-apps) in order to add example to the library.

Thanks

**Comment by cpq** [comment]
https://github.com/mongoose-os-apps/mq135 please

**Comment by kanigirilalasa** [comment]
hey 
it was not working on my mos tool 
saying unable to execute adc file in mq135 library?
what to do ?
