### ISSUE TITLE
The library uses `adc` which is not included in `mos.yml`

### ISSUE THREAD

**Issue by nliviu** [mongoose-os-libs/mq135#2]
Add 
```
 - origin: https://github.com/mongoose-os-libs/adc
```
in `mos.yml`.

**Comment by cpq** [comment]
added you as admin. Please send a PR to the author. Merge yourself if there is no response.
Thank you!

**Comment by aoudiamoncef** [comment]
I can't make tests, i haven't the hardware. I'm waiting for your pull request. Thank you.

**Comment by nliviu** [comment]
No need to have the device. You add `load('api_adc.js');` and call `ADC.read`.
That means this library depends on `adc`.

Here is the [PR](https://github.com/mongoose-os-libs/mq135/pull/3)
